fm/models/Lang.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "lang".
 *
 * @property integer $id
 * @property string $name
 *
 * @property LangContent[] $langContents
 * @property Project[] $projects
 * @property Project[] $projects0
 */
class Lang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent()
    {
        return $this->hasOne(LangContent::className(), ['lang_id' => 'id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurrent()
    {
        return $this->hasOne(LangContent::className(), ['lang_id' => 'id'])->andWhere([
            'lang' => Yii::$app->loc->get()
        ]);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContents()
    {
        return $this->hasMany(LangContent::className(), ['lang_id' => 'id']);
    }
}

fm/models/Project.php
<?php

namespace app\models;
use app\components\ImageColor;
use Yii;

/**
 * This is the model class for table "project".
 *
 * @property integer $id
 * @property string $date_from
 * @property string $date_to
 * @property integer $description
 * @property integer $contribution
 * @property string $name
 * @property string $link
 * @property string $code_link
 * @property string $image
 *
 * @property Lang $contribution0
 * @property Lang $description0
 * @property ProjectTag[] $projectTags
 */
class Project extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_from', 'date_to'], 'safe'],
            [['description', 'contribution'], 'required'],
            [['description', 'contribution'], 'integer'],
            [['name', 'link', 'code_link', 'image'], 'string', 'max' => 255],
            [['contribution'], 'exist', 'skipOnError' => true, 'targetClass' => Lang::className(), 'targetAttribute' => ['contribution' => 'id']],
            [['description'], 'exist', 'skipOnError' => true, 'targetClass' => Lang::className(), 'targetAttribute' => ['description' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date_from' => Yii::t('app', 'Date From'),
            'date_to' => Yii::t('app', 'Date To'),
            'description' => Yii::t('app', 'Description'),
            'contribution' => Yii::t('app', 'Contribution'),
            'name' => Yii::t('app', 'Name'),
            'link' => Yii::t('app', 'Link'),
            'code_link' => Yii::t('app', 'Code Link'),
            'image' => Yii::t('app', 'Image'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContribution_()
    {
        return $this->hasOne(Lang::className(), ['id' => 'contribution']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDescription_()
    {
        return $this->hasOne(Lang::className(), ['id' => 'description']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])->viaTable(
            'project_tag', ['project_id' => 'id']
        );
    }

    public function getDateFromText(){
        return date("m.Y", strtotime($this->date_from));
    }
    public function getDateToText(){
        return date("m.Y", strtotime($this->date_to));
    }
    /**
     * @return string = link with current domain inside
     */
    public function getLinkText(){
        return str_replace('domain.com', isset($_SERVER['HTTP_HOST'])?$_SERVER['HTTP_HOST'] : 'ururu.ru', $this->link);
    }
    /**
     * @return array(2) = [min_date, max_date]
     */
    public static function utterDates(){
    	$C = Yii::$app->cache;
    	$got = $C->get('utter_dates');
    	if($got)
    		return $got;
    	$minDate = self::find() 
		    ->select('min(date_from)') 
		    ->scalar();
	    $maxDate = self::find() 
		    ->select('max(date_to)') 
		    ->scalar();

		if(!$got)
			$C->set('utter_dates', [$minDate, $maxDate]);
		return [$minDate, $maxDate];
    }
    /**
     * @return color, that calculated from Projecr's image
     */
    public function getImageColor(){
        $path = \Yii::getAlias('@webroot') . '/img/project/';
        $iColor = new ImageColor;
        return $iColor->get($path . $this->image);
    }
}

fm/controllers/ProjectsController.php
<?php

namespace app\controllers;
use \app\models\Project;
use \app\models\Tag;
use yii\helpers;
class ProjectsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $filters = array_filter(explode(':', \Yii::$app->request->get('params')));
        $tags = Tag::find()->all();
        $types = [];
        foreach ($tags as $t) {
            $types[$t->type] = isset($types[$t->type]) ? array_merge($types[$t->type], [$t]) : [$t];
        }
        return $this->render('index', [
            'projects' => Project::find()->orderBy('date_from')->all(),
            'tags' => $tags,
            'types' => $types,
            'tagMap' => \Yii::$app->tagMap->get(),
            'utterDates' => Project::utterDates(),
            'filters' => $filters,
            'canonicalUrl' => \yii\helpers\Url::canonical()
        ]);
    }

    public function actionView()
    {
        return $this->render('view');
    }
    public function actionInd(){
        $project_id = (int)(\Yii::$app->request->get('params'));
        $project = Project::findOne($project_id);
        // if(!$project_id)
            // return redirect('/');
        return $this->render('ind', [
            'utterDates' => Project::utterDates(),
            'project' => $project
        ]);
    }

    public function behaviors()
    {
        return [
            'pageCache' => [
                'class' => 'yii\filters\PageCache',
                'only' => ['index'],
                'duration' => 60*60,
                
                'variations' => [
                    \Yii::$app->loc->get(),
                    \Yii::$app->request->get('params')
                ]
            ],
        ];
    }

}

fm/views/projects/datebar.php
<?php 
	if(!function_exists('dateIval')){
		function dateIval($from, $to){
			$begin = new DateTime( $from);
			$end = new DateTime( $to );
			$end = $end->modify( '+1 day' ); 

			$interval = new DateInterval('P1M');
			$daterange = new DatePeriod($begin, $interval ,$end);
			$months = [];
			foreach ($daterange as $dr) {
				$months []= $dr->format('m.Y');
			}
			return $months;
		};
		function thinOut($a){
			$r = [];
			foreach($a as $k => $_a)
				if($k % 6 == 0)
					$r []= $_a;
				else
					$r []= '';
			return $r;
		}
		function minText($txt){
			$p = explode('.', $txt);
			return (int)$p[0] . '.' .substr($txt, -2, 2);
		}

	};
	$months = dateIval($utters[0], $utters[1]);
	$thinMonths = thinOut($months);
	$datesIn = dateIval($dates[0], $dates[1]);
	$width = 'width:' . 100/count($months) . '%';
	// echo '<br>';
	// echo $dates[0];
	// echo '<br>';
	// echo $dates[1];
	// echo '<br>';
	// print_r($datesIn);
	// echo '<br>';
	// print_r($months);
?>
<div class="datebar">
	<div class="labels">
		<table>
			<tr>
				<?php foreach ($months as $k => $m): ?>
					<td style="<?php echo $width; ?>">
						<div class="kuku-text">
							<?php if($thinMonths[$k]): ?>	
								<span class="date-point">&nbsp;</span>
								<?php echo minText($thinMonths[$k]); ?>
							<?php endif; ?>	
							
						</div>
					</td>
				<?php endforeach ?>
			</tr>
		</table>
	</div>
	<div class="pic">
		<table>
			<?php foreach ($months as $m): ?>
				<td title="<?php echo $m; ?>" style="<?php echo $width; ?>" class="<?php echo in_array($m, $datesIn) ? 'active' : ''; ?>">
					
				</td>
			<?php endforeach ?>
		</table>
	</div>
</div>

fm/views/projects/ind.php
<?php 
	
	use app\assets\MixitupAsset;
	use app\assets\ProjectsAsset;
	MixitupAsset::register($this);
	ProjectsAsset::register($this);
	function tagFilter($tag){
		return str_replace('+', 'p', $tag);
	}
	$this->title = $project->name;
?>
<style>
	.project{
		display: block;
		border: none;
	}
	.project:after{
		display: none;
	}
	#ifr{
		width:100%;
		height:700px;
	}
</style>
<div class="project">
	<?php echo $this->render('project-info', [
		'p' => $project, 'utterDates' => $utterDates, 'ind' => true
	]); ?>
</div>
<h3>
	<a href="http://<?php echo $project->linkText?>" target="_blank">
		<span class="glyphicon glyphicon-link" style="font-size:20px">
			
		</span>	
		<?php echo Yii::$app->locTitle->get('#go_to_href_title'); ?>
	</a>
	

</h3>
<iframe id="ifr" src="http://<?php echo $project->linkText; ?>" frameborder="0">
	
</iframe>
<script type="text/javascript">
	window.tagMap = [];
	window.filters = [];
</script>

fm/views/projects/index.php
<?php 
	
	use app\assets\MixitupAsset;
	use app\assets\ProjectsAsset;
	use app\components\TagsWidget;
	MixitupAsset::register($this);
	ProjectsAsset::register($this);
	function tagFilter($tag){
		return str_replace('+', 'p', $tag->name);
	}
	$this->title = Yii::$app->locTitle->get('#menu_projects_title');
?>
<h1>
	<?php echo Yii::$app->locTitle->get('#menu_projects_title'); ?>
</h1>
<div class="row filter-tags">
	<?php 
		$class = (int)(12/count($types));
	?>
	<?php foreach ($types as $type=>$tags): ?>
		<div class="col-md-<?php echo $class;?>">
			<div>
				<h4><?php echo Yii::$app->locTitle->get('#'.$type); ?></h4>
			</div>
			<?php echo TagsWidget::widget(['tags' => $tags]) ?>
		</div>
	<?php endforeach ?>
</div>
<div class="row" id="projects">
<?php foreach($projects as $k => $p): ?>
		
			
		
		<div 
			class="col-md-6 col-xs-12 project mix <?php echo implode(' ', array_map('tagFilter', $p->tags));?>"
			image="/img/project/<?php echo $p->image;?>"	
		>
			<div class="abs text-container">
				<?php echo $this->render('project-info', ['p' => $p, 'utterDates' => $utterDates]); ?>
			</div>
		</div>
	
<?php endforeach; ?>
</div>

<script type="text/javascript">
	window.tagMap = <?php echo json_encode($tagMap); ?>;
	window.filters = <?php echo json_encode($filters); ?>;
	window.canonicalUrl = '<?php echo $canonicalUrl; ?>';
</script>

fm/views/projects/project-info.php
<?php
	use yii\helpers\Url;
	use app\components\TagsWidget;
	use app\assets\ViewerJsAsset;
	ViewerJsAsset::register($this);
	$titleTag = isset($ind) ? 'h1' : 'h3';
?>
<<?php echo $titleTag; ?>>
	<?php echo $p->name;?>
</<?php echo $titleTag; ?>>

<table class="parameters">
	<tr>
		<td class="param-col">
			<?php echo Yii::$app->locTitle->get('#dates_title'); ?>
		</td>
		<td class="param-col">
			<?php echo $p->dateFromText . ' - ' . $p->dateToText;?>		
			<?php 
				echo $this->render('datebar', [
					'utters' => $utterDates,
					'dates' => [$p->date_from, $p->date_to]
				])
			 ?>
		</td>
	</tr>
	<tr>
		<td class="param-col">
			
			<?php echo Yii::$app->locTitle->get('#description_title'); ?>:
					
		</td>
		<td class="param-col">
			<?php echo $p->description_->current->content;?>
		</td>
	</tr>
	<tr>
		<td class="param-col">
			
			<?php echo Yii::$app->locTitle->get('#contribution_title'); ?>:

		</td>
		<td class="param-col">
			<?php echo $p->contribution_->current->content;?>
		</td>
	</tr>
	<tr>
		<td class="param-col">
			<?php echo Yii::$app->locTitle->get('#tags_title'); ?>
		</td>
		<td class="param-col">
			<?php echo TagsWidget::widget(['tags' => $p->tags]); ?>
		</td>
	</tr>
	<?php if(!isset($ind)): ?>
	<tr>
		<td class="param-col">
			<?php echo Yii::$app->locTitle->get('#link_title'); ?>
		</td>
		<td class="param-col">
			<a href="<?php echo Url::to('/projects/ind/'.$p->id);?>" target="_blank">
				<span class="glyphicon glyphicon-link" style="font-size:20px">
					
				</span>
			</a>
		</td>
	</tr>
	<tr>
		<td class="param-col">
			<?php echo Yii::$app->locTitle->get('#picture_title'); ?>
		</td>
		<td class="param-col">
			<span class="glyphicon glyphicon-eye-open view-picture"></span>
		</td>
	</tr>
<?php endif; ?>
</table>