fm/controllers/ContactsController.php
<?php

namespace app\controllers;

class ContactsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

fm/controllers/ProjectsController.php
<?php

namespace app\controllers;
use \app\models\Project;
use \app\models\Tag;
use yii\helpers;
class ProjectsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $filters = array_filter(explode(':', \Yii::$app->request->get('params')));
        $tags = Tag::find()->all();
        $types = [];
        foreach ($tags as $t) {
            $types[$t->type] = isset($types[$t->type]) ? array_merge($types[$t->type], [$t]) : [$t];
        }
        return $this->render('index', [
            'projects' => Project::find()->orderBy('date_from')->all(),
            'tags' => $tags,
            'types' => $types,
            'tagMap' => \Yii::$app->tagMap->get(),
            'utterDates' => Project::utterDates(),
            'filters' => $filters,
            'canonicalUrl' => \yii\helpers\Url::canonical()
        ]);
    }

    public function actionView()
    {
        return $this->render('view');
    }
    public function actionInd(){
        $project_id = (int)(\Yii::$app->request->get('params'));
        $project = Project::findOne($project_id);
        // if(!$project_id)
            // return redirect('/');
        return $this->render('ind', [
            'utterDates' => Project::utterDates(),
            'project' => $project
        ]);
    }

    public function behaviors()
    {
        return [
            'pageCache' => [
                'class' => 'yii\filters\PageCache',
                'only' => ['index'],
                'duration' => 60*60,
                
                'variations' => [
                    \Yii::$app->loc->get(),
                    \Yii::$app->request->get('params')
                ]
            ],
        ];
    }

}

fm/views/layouts/lang.php
<?php
use yii\helpers\url;
?>
<<?=isset($mobile) ? 'div':'li';?> class="<?=isset($mobile) ? 'lang-external-button visible-xs':'hidden-xs';?>">
    
            
            <table class="centerer">
            	<tr class="centerer-tr">
            		<td></td>
            	</tr>
            	<tr class="centerer-tr">
            		<td>
	            		<form action="<?=Url::current();?>" method="GET" class="lang">
					        <input type="hidden" name="lang" value="<?=Yii::$app->loc->to()?>">
					        <button class="lang-button">
	            				<img src="/img/lang/<?=Yii::$app->loc->to()?>.png" alt="">
	            			</button>
	    				</form>
            		</td>
            	</tr>
            	<tr class="centerer-tr">
            		<td></td>
            	</tr>
            </table>
			
        
</<?=isset($mobile) ? 'div':'li';?>>

fm/views/layouts/logo.php
<a class="navbar-brand" 
    href="/"
    <?=Yii::$app->request->pathInfo?'':'onclick="return false;"';?>
>
    <div class="logo-container">

        
        <table class="centerer">
            <tr class="centerer-tr">
                <td></td>
            </tr>
            <tr class="centerer-tr">
                <td>
                    <table class="logo">
                        <tr>
                            <td>
                                <div part-name="lt" class="part white"></div>
                            </td>
                            <td>
                                <div part-name="rt" class="part round green"></div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div part-name="lb" class="part blue"></div>
                            </td>
                            <td>
                                <div part-name="rb" class="part"></div>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr class="centerer-tr">
                <td></td>
            </tr>
        </table>
    </div>
</a>

fm/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use yii\helpers\url;
use app\assets\AppAsset, app\assets\CustomAsset;

AppAsset::register($this);
CustomAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="icon" type="image/png" href="apple-favicon.png" />
    <base href="/"> 
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter43146424 = new Ya.Metrika({ id:43146424, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/43146424" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <nav id="w0" class="navbar-inverse navbar-fixed-top navbar" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <?=$this->render('lang', ['mobile' => 'asd']);?>
                <button type="button" class="navbar-toggle custom" data-toggle="collapse" data-target="#w0-collapse"><span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span></button>
                        <?php echo $this->render('logo'); ?>
                    </div>
            <div id="w0-collapse" class="collapse navbar-collapse">
                <ul id="w1" class="navbar-nav navbar-right nav">
                    <?php
                        $urls = [
                            [
                                'title' => '#menu_projects_title',
                                'url' => 'projects/index'
                            ],
                            [
                                'title' => '#contacts',
                                'url' => 'contacts/index'
                            ]
                        ];
                    ?>
                    <?php foreach($urls as $u): ?>
                        <li class="custom <?=$u['url']==Yii::$app->request->pathInfo?'active':''?>">
                            <a href="<?=Url::toRoute($u['url']);?>">
                                <?=Yii::$app->locTitle->get($u['title']);?>    
                            </a>
                        </li>
                    <?php endforeach; ?>
                    
                    <?=$this->render('lang');?>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left"></p>

        <p class="pull-right"></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>